Repository shivanshsinghx365/Computer-Science-Resources, pull requests merged in 2022-10, with the labels that each got.

#4 Create BOOKS.md
  Notes/BOOKS.md
Labels: hacktoberfest-accepted

#5 added learning material
  Python/Learning-Material
Labels: hacktoberfest, hacktoberfest-accepted

#9 Added custom react hooks
  WebDev/ReactJs/customHooks/useCounter.js
  WebDev/ReactJs/customHooks/useInput.js
  WebDev/ReactJs/customHooks/useLocalStorage.js
  WebDev/ReactJs/customHooks/useToggle.js
Labels: hacktoberfest, hacktoberfest-accepted

#10 add cheat sheets
  Cheat Sheets/CheatSheets.md
Labels: hacktoberfest, hacktoberfest-accepted

#12 added resources for learning java
  Java/learn_java.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#13 created practice_java
  Java/practice_java.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#14 added learn_cpp
  Cpp/learn_cpp.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#15 added practice_cpp.md
  Cpp/practice_cpp.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#16 add yolo transfer learning tutorial
  AI-ML/yolo-transfer-learning/YOLO_Transfer_Learning_Tutorial.ipynb
  AI-ML/yolo-transfer-learning/creating-files-data-and-name.py
  AI-ML/yolo-transfer-learning/creating-train-and-test-txt-files.py
Labels: hacktoberfest, hacktoberfest-accepted

#19 Resolved Issue #7 as part of Hacktoberfest 2022
  Blockchain/resources-blockchain
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#17 Added DSA sheet by Arsh Goyal
  DevOps
  Practice Sheets/DSA Day-wise Siddharth Singh.xlsx
  Practice Sheets/DSA Sheet by Arsh (45 Days Plan).xlsx
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#24 Added resources for Computer Networking- Resolved issue #21
  Computer Networking/computer-networking-resources
Labels: hacktoberfest-accepted

#25 Added DBMS resources for placements and university exams as part of Hacktoberfest
  DBMS/DBMS-Resources
Labels: hacktoberfest, hacktoberfest-accepted

#26 Update
  Youtube & Website/Youtube.md
Labels: hacktoberfest, hacktoberfest-accepted

#28 Updated the README.MD & CONTRIBUTING.MD and also added various resources in DevOps to get started with
  CONTRIBUTING.md
  DevOps/Resources.md
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#29 Added OS Resources
  OS/OS-Resources
Labels: hacktoberfest, hacktoberfest-accepted

#32 Added Practice Sites
  Practice Sites/Practice Sites.md
Labels: hacktoberfest, hacktoberfest-accepted

#31 Added Quicksort Python One-liner
  Code Snippets and Oneliners/Quicksort Python One-liner.py
Labels: hacktoberfest, hacktoberfest-accepted

#34 DSA Revision Guide
  DSA/DSA-Revision-Guide.pdf
Labels: hacktoberfest, hacktoberfest-accepted

#35 Update OS-Resources
  OS/OS-Resources
Labels: hacktoberfest, hacktoberfest-accepted

#36 Update BOOKS.md
  Notes/BOOKS.md
Labels: hacktoberfest, hacktoberfest-accepted

#37 Added Data Science resources
  Data-Science/Data Science.md
Labels: hacktoberfest, hacktoberfest-accepted

#39 Add all binary tree traversals code snippets
  Code Snippets and Oneliners/CPP/BinaryTree/InOrderTraversal.cpp
  Code Snippets and Oneliners/CPP/BinaryTree/LevelOrderTraversal.cpp
  Code Snippets and Oneliners/CPP/BinaryTree/PostOrderTraversal.cpp
  Code Snippets and Oneliners/CPP/BinaryTree/PreOrderTraversal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#41 Update Youtube.md
  Youtube & Website/Youtube.md
Labels: hacktoberfest, hacktoberfest-accepted

#42 Update CheatSheets.md
  Cheat Sheets/CheatSheets.md
Labels: hacktoberfest, hacktoberfest-accepted

#43 added Roadmap for DevOps
  DevOps/Roadmap.md
Labels: hacktoberfest, hacktoberfest-accepted

#44 Added Android resources
  Android/Android.md
Labels: hacktoberfest, hacktoberfest-accepted

#45 adds resources and roadmaps for flutter dev and game dev
  Flutter/.gitkeep
  Flutter/Resources.md
  Flutter/Roadmaps.md
  Game Development/.gitkeep
  Game Development/Resources.md
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added Resources for Backend Web Development as part of Hacktoberfest
  WebDev/Backend Development Resources
Labels: hacktoberfest, hacktoberfest-accepted

#47 Added Python learning resources
  Python/Learning-Material
Labels: hacktoberfest, hacktoberfest-accepted

#48 Add Circular Queue Implementation in C
  Code Snippets and Oneliners/C/CircularQueue.c
Labels: hacktoberfest, hacktoberfest-accepted

#49 Added free Python learning resources
  Python/Learning-Material
Labels: hacktoberfest, hacktoberfest-accepted

#50 Added Data-Science courses and resources
  Data-Science/Data Science.md
Labels: hacktoberfest, hacktoberfest-accepted

#51 Create computer-organization-resources
  Computer Organization/computer-organization-resources
Labels: hacktoberfest, hacktoberfest-accepted

#52 Included frontend web resources
  WebDev/Frontend Development Resources
Labels: hacktoberfest, hacktoberfest-accepted

#54 created new folder Competitive Programming and added the relevant res…
  Competitive Programming/.gitkeep
  Competitive Programming/Resources.md
Labels: hacktoberfest, hacktoberfest-accepted

#55 added some C++ links
  Cpp/learn_cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#57 Basic commands of git
  DevOps/git-cheat-sheet-education.pdf
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#59 Added a folder for quantitative finance interviews and also added the…
  Quantitative Finance Interview/Resources.md
Labels: enhancement, hacktoberfest, hacktoberfest-accepted

#60 Added Java and Javascript Code Snippets
  Code Snippets and Oneliners/Java/House robber.java
  Code Snippets and Oneliners/Java/Longest increase distance.java
  Code Snippets and Oneliners/Java/Minimum path sum.java
  Code Snippets and Oneliners/Java/Pascals triangle,java
  Javascript/.gitkeep
  Javascript/learn_javascript.md
  Javascript/practice_javascript.md
Labels: hacktoberfest, hacktoberfest-accepted

#61 Added data visualization resources
  Data Visualization/.gitkeep
  Data Visualization/data visulization tools.md
  Data Visualization/resources.md
Labels: hacktoberfest, hacktoberfest-accepted

#62 added resources and portals to already empty Internship/job folder
  Internships & Job Portals/portals.md
Labels: hacktoberfest, hacktoberfest-accepted

#65 Added resources under multiple categories
  AI-ML/Resources.md
  Android/Android.md
  Blockchain/resources-blockchain
  Cheat Sheets/CheatSheets.md
  Competitive Programming/Resources.md
  Computer Networking/computer-networking-resources
  Computer Organization/computer-organization-resources
  DBMS/DBMS-Resources
  Data-Science/Data Science.md
  DevOps/Resources.md
Labels: hacktoberfest, hacktoberfest-accepted

#70 added Segment tree code for CP
  Code Snippets and Oneliners/Segment Tree.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 add design cheatsheets and hr interview questionnaire
  Cheat Sheets/CheatSheets.md
  Interviews/interview.md
Labels: enhancement, hacktoberfest

#73 Modified Resources.MD file
  AI-ML/Resources.md
Labels: hacktoberfest-accepted

#76 Circular linked list
  Code Snippets and Oneliners/C/circularlinkedlist.c
Labels: hacktoberfest, hacktoberfest-accepted

#79 Polymorphism
  Cpp/learn_cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#81 Update learn_cpp.md
  Cpp/learn_cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#82 Update learn_cpp.md
  Cpp/learn_cpp.md
Labels: hacktoberfest, hacktoberfest-accepted

#83 added code for insertion in doubly linked list
  Code Snippets and Oneliners/C/doublylinkedlist.c
Labels: hacktoberfest, hacktoberfest-accepted

#85 Adding Python resources.
  Python/Learning-Material
Labels: hacktoberfest-accepted

#86 Update resources-blockchain
  Blockchain/resources-blockchain
Labels: hacktoberfest, hacktoberfest-accepted

#87 Update computer-networking-resources
  Computer Networking/computer-networking-resources
Labels: hacktoberfest-accepted

#88 added cyber security resources
  cyber Security/.gitkeep
  cyber Security/resources-cyberSec
Labels: hacktoberfest, hacktoberfest-accepted

#91 Added some more youtube channels
  Youtube & Website/Youtube.md
Labels: hacktoberfest, hacktoberfest-accepted
